#!/usr/bin/env bash

set -e

# Find design files
files=$(ls ../derivatives/fsl/sub-??/floc*/ses-?.feat/design.p*)
for f in ${files}; do
    echo "Cropping ${f} ..."
    convert ${f} -gravity north -crop 100x73% +repage ${f}
done
