#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
    echo "Setting number of cores to 1 ..."
    n_cores=1
else
    n_cores=$1
fi

subs=$(ls -d ../derivatives/fsl/sub-??)

i=0
for sdir in ${subs}; do
    sub=$(basename ${sdir})

    for task in flocBLOCKED flocER; do
        template=template_floc_runlevel2.fsf
        outputdir=../derivatives/fsl/${sub}/${task}/runlevel

        if [ -d ${outputdir}.gfeat ]; then
    	    echo "Skipping ${outputdir}, because it's already done!"
	    continue
        fi
	
        #ses1cope4=/home/lsnoek1/spinoza_data/ni-edu/bids/derivatives/fsl/${sub}/${task}/ses-1.feat/stats/cope4.nii.gz
	#ses2cope4=/home/lsnoek1/spinoza_data/ni-edu/bids/derivatives/fsl/${sub}/${task}/ses-2.feat/stats/cope4.nii.gz
	#ses1cope5=/home/lsnoek1/spinoza_data/ni-edu/bids/derivatives/fsl/${sub}/${task}/ses-1.feat/stats/cope5.nii.gz
	#ses2cope5=/home/lsnoek1/spinoza_data/ni-edu/bids/derivatives/fsl/${sub}/${task}/ses-2.feat/stats/cope5.nii.gz
        ses1=/home/lsnoek1/spinoza_data/ni-edu/bids/derivatives/fsl/${sub}/${task}/ses-1.feat
	ses2=/home/lsnoek1/spinoza_data/ni-edu/bids/derivatives/fsl/${sub}/${task}/ses-2.feat

        export outputdir ses1 ses2
        fsf=../derivatives/fsl/fsf/${sub}_task-${task}_runlevel.fsf
	envsubst < ${template} > ${fsf}
	    
	echo "Running FEAT for ${sub}, ${ses}, with task ${task} ..."
	feat ${fsf} &
	    
	i=$(($i + 1))
	if [ $((${i} % ${n_cores})) == 0 ]; then
	    wait  # wait before other processes are finished
        fi

    done
done

wait  # make sure to wait if not everything's finished yet
